# Generated by Django 3.2.9 on 2021-11-27 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_img/')),
                ('book_name', models.CharField(max_length=200, verbose_name='도서명')),
                ('publisher', models.CharField(max_length=100, verbose_name='출판사')),
                ('author', models.CharField(max_length=100, verbose_name='저자')),
                ('publication_date', models.CharField(blank=True, max_length=10, verbose_name='출판일')),
                ('pages', models.CharField(max_length=10000, verbose_name='페이지 수')),
                ('isbn', models.CharField(max_length=25, unique=True, verbose_name='ISBN')),
                ('description', models.CharField(max_length=10000, verbose_name='소개')),
                ('link', models.URLField(blank=True, verbose_name='원본링크')),
                ('hold', models.IntegerField(blank=True, verbose_name='보유권수')),
            ],
            options={
                'db_table': 'book_info',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='RentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_status', models.BooleanField(verbose_name='반납여부')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookinfo', verbose_name='대출도서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='대출회원')),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='rent_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookInfo', to='books.rentinfo'),
        ),
    ]
