# Generated by Django 3.2.9 on 2021-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='표지이미지'),
        ),
    ]
